config/routes.rb
Exp::Application.routes.draw do
  resources :products

  get 'address', :to => "products#address_info", :as => :info
  post 'addresscreate', :to => "products#address_create", :as => :address

  root :to => 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :product
  attr_accessible :email, :product_id, :stripe_card_token, :stripe_customer_token



  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email,plan: product_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :product
  has_attached_file :image, :styles => {:medium => "640x480>", :thumb => "100x100>"}
  attr_accessible :image


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title,:price, :assets_attributes, :addresses_attributes
  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true
  has_many :addresses
  #accepts_nested_attributes_for :addresses, :allow_destroy => true

  extend FriendlyId
  friendly_id :title, use: :slugged


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
     1.times { @product.assets.build }
    #1.times { @product.addresses.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    1.times { @product.assets.build }
  end

  # POST /products
  # POST /products.json
  def create
    
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def address_info
    @address = Address.new(:product_id => params[:id])
    @product = Product.find_by_id(params[:id])
    @price = @product.price
    #1.times { @product.addresses.build }

  end
  def address_create


    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save_with_payment
        flash[:notice] = 'Thanks for Purchase!'
        format.html { redirect_to root_url }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/","application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => "pk_test_EdzRNSxqtFoHpkUdziJGSwoZ" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
      <br/>
      <%= f.label :price %>
      <br/>
      <%= f.text_field :price %>
    </div>
    <p>
      <%#= f.file_field :image %>

    </p>
    <!--<div>
      <%#= f.fields_for :addresses do |builder| %>
          <p>
            <%#= builder.text_field :email %>
          </p>
      <%# end %>
    </div>-->
    <div>
     <%= f.fields_for :assets do |asset_fields| %>
        <p>
         <%= asset_fields.file_field :image %>
        </p>
     <% end %>
    </div>



    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/products/address_info.html.erb
<%= form_for @address, :url => address_path, :html => {:multipart => true} do |f| %>

    <div class="field">

      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <%= f.hidden_field :product_id %>

    <%= f.hidden_field :stripe_card_token %>
    <%= f.hidden_field :stripe_customer_token, :value => "123" %>

    <% if @address.stripe_card_token.present? %>
        Credit card has been provided.
    <% else %>
        <div class="field">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_code, "Security Code on Card (CVV)" %>
          <%= text_field_tag :card_code, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_month, "Card Expiration" %>
          <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
          <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
        </div>
    <% end %>
    <div id="stripe_error">
      <noscript>
        JavaScript is not enabled and is required this form. First enable it in your browser settings.
      </noscript>
    </div>

    <%= f.submit %>

<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td><%= link_to 'buy',info_path(:id => product.id) %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Title:</b>
  <%#= image_tag @product.assets.image.url %>
  <%= image_tag @product.assets.first.image.url %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>